# Generated by Django 2.1.9 on 2019-06-11 03:14

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('home', '0005_auto_20190610_0142'),
    ]

    operations = [
        migrations.CreateModel(
            name='SinglePageApp',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(max_length=255)),
                ('body', wagtail.core.fields.StreamField([('translations', wagtail.core.blocks.StructBlock([('word', wagtail.core.blocks.CharBlock(max_length=255, required=True)), ('sp', wagtail.core.blocks.CharBlock(max_length=255))]))])),
            ],
        ),
    ]
