# Generated by Django 2.1.9 on 2019-06-11 03:24

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_singlepageapp_translation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translation',
            name='body',
            field=wagtail.core.fields.StreamField([('translations', wagtail.core.blocks.StructBlock([('word', wagtail.core.blocks.CharBlock(max_length=255, required=True)), ('en', wagtail.core.blocks.CharBlock(max_length=255)), ('sp', wagtail.core.blocks.CharBlock(max_length=255)), ('fr', wagtail.core.blocks.CharBlock(max_length=255))]))]),
        ),
    ]
